In [6]:

import pandas as pd
from IPython.display import display


archivo = 'oferta_academicav2.2.xlsx'
all_sheets = pd.read_excel(archivo, sheet_name=None, engine='openpyxl')

for nombre, df in all_sheets.items():
    print("Hoja:", nombre, "— filas:", df.shape[0], "columnas:", df.shape[1])
    display(df)

Hoja: area — filas: 3 columnas: 2

   id_area                               nombre_area
0        1  Ingeniería y Ciencias Físico Matemáticas
1        2                Ciencias Médico Biológicas
2        3       Ciencias Sociales y Administrativas

Hoja: escuela — filas: 26 columnas: 2

    id_escuela              nombre_escuela
0            1      CICS Unidad Milpa Alta
1            2     CICS Unidad Santo Tomás
2            3                        ENBA
3            4                        ENCB
4            5                       ENMyH
5            6     ESCA Unidad Santo Tomás
6            7         ESCA Unidad Tepepan
7            8                       ESCOM
8            9                         ESE
9           10                        ESEO
10          11                        ESFM
11          12    ESIA Unidad Tecamachalco
12          13         ESIA Unidad Ticomán
13          14       ESIA Unidad Zacatenco
14          15  ESIME Unidad Azcapotzalco
15          16      ESIME Unidad Culhuacán
16          17        ESIME Unidad Ticomán
17          18      ESIME Unidad Zacatenco
18          19                      ESIQIE
19          20                        ESIT
20          21                         ESM
21          22                         EST
22          23                       UPIBI
23          24                       UPIEM
24          25                     UPIICSA
25          26                      UPIITA

Hoja: carrera — filas: 66 columnas: 3

    carrera_id                            nombre_carrera  id_area
0            1                    Ingeniería Aeronáutica        1
1            2                      Ingeniería Ambiental        1
2            3                      Ingeniería Biomédica        1
3            4                        Ingeniería Biónica        1
4            5                     Ingeniería Bioquímica        1
..         ...                                       ...      ...
61          62     Licenciatura en Mercadotecnia Digital        3
62          63        Licenciatura en Negocios Digitales        3
63          64  Licenciatura en Negocios Internacionales        3
64          65    Licenciatura en Relaciones Comerciales        3
65          66                   Licenciatura en Turismo        3

[66 rows x 3 columns]

Hoja: habilidad — filas: 253 columnas: 2

    id_habilidad                                        descripcion
0           H001  Diseño, construcción, mantenimiento y operació...
1           H002  Proyección y puesta en operación de plantas e ...
2           H003  Investigación, adaptación y desarrollo de nuev...
3           H004  Planeación, dirección y gestión de empresas de...
4           H005  Aplicación de normatividad técnica, jurídica, ...
..           ...                                                ...
248         H249  Formulación de planes de negocios comerciales ...
249         H250  Planeación, dirección y gestión de operaciones...
250         H251  Diseño, desarrollo y comercialización de produ...
251         H252  Aplicación de estándares internacionales de ca...
252         H253  Preservación de la riqueza natural, cultural y...

[253 rows x 2 columns]

Hoja: carrera_habilidad — filas: 336 columnas: 2

    id_carrera id_habilidad
0         C001         H001
1         C001         H002
2         C001         H003
3         C001         H004
4         C001         H005
..         ...          ...
331       C066         H250
332       C066         H251
333       C066         H252
334       C066         H253
335       C066         H023

[336 rows x 2 columns]

####procesa archivo excel de escuelas, carreras, area