# Script de Inyeccion de datos
En este archivo, inyectamos los datos homologados y normalizados

### IMPORTACIONES DE BIBLIOTECAS NECESARIAS

In [15]:
import polars as pl
from IPython.display import display
from pydantic import BaseModel

### Constantes del Notebook
Aqui se definen las constantes que se necesiten para subir los archivos

In [16]:
FILE_PATH = './layouts/oferta_academicav2.2.xlsx'  # cambiar por ruta del archivo que se desea leer
SHEETS_NAMES = ['area', 'escuela', 'carrera']  # nombre de las hojas que se desean procesar

### Modelos de pydantic

en este apartado estan los modelos para subir a la base de datos los datos correspondientes sin romper la tabla

In [17]:
class Area(BaseModel):
    area_id: int
    nombre_area: str

class Escuela(BaseModel):
    escuela_id: int
    nombre_escuela: str

class Carrera(BaseModel):
    carrera_id: int
    nombre_carrera: str
    id_area: int

### Funciones de procesamiento

aqui estan todas las funciones para procesar el excel, dependiendo de la hoja lo procesa de manera distinta

In [ ]:

def read_excel_file(file_path: str, sheet_name: str) -> pl.DataFrame:
    df_sheet = pl.read_excel(file_path, sheet_name=sheet_name)
    return df_sheet

def view_excel_sheets(df: pl.DataFrame, sheet_name: str):
    print(f"Sheet: {sheet_name}")
    display(df)

### Ejecucion

aqui se ejecuta el script, haciendo que se procese y se suba la informacion

In [13]:
if __name__ == "__main__":
    for sheet_name in SHEETS_NAMES:
        df = read_excel_file(FILE_PATH, sheet_name)
        view_excel_sheets(df, sheet_name)

Sheet: area

/var/folders/5c/1h_2rjpj3wg1lps5yq7kg2740000gn/T/ipykernel_63983/396950821.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df_sheet = pl.read_excel(file_path, sheet_name=sheet_name)

shape: (3, 2)
┌─────────┬─────────────────────────────────┐
│ id_area ┆ nombre_area                     │
│ ---     ┆ ---                             │
│ i64     ┆ str                             │
╞═════════╪═════════════════════════════════╡
│ 1       ┆ Ingeniería y Ciencias Físico M… │
│ 2       ┆ Ciencias Médico Biológicas      │
│ 3       ┆ Ciencias Sociales y Administra… │
└─────────┴─────────────────────────────────┘

Sheet: escuela

shape: (26, 2)
┌────────────┬─────────────────────────┐
│ id_escuela ┆ nombre_escuela          │
│ ---        ┆ ---                     │
│ i64        ┆ str                     │
╞════════════╪═════════════════════════╡
│ 1          ┆ CICS Unidad Milpa Alta  │
│ 2          ┆ CICS Unidad Santo Tomás │
│ 3          ┆ ENBA                    │
│ 4          ┆ ENCB                    │
│ 5          ┆ ENMyH                   │
│ …          ┆ …                       │
│ 22         ┆ EST                     │
│ 23         ┆ UPIBI                   │
│ 24         ┆ UPIEM                   │
│ 25         ┆ UPIICSA                 │
│ 26         ┆ UPIITA                  │
└────────────┴─────────────────────────┘

Sheet: carrera

shape: (66, 3)
┌────────────┬─────────────────────────────────┬─────────┐
│ carrera_id ┆ nombre_carrera                  ┆ id_area │
│ ---        ┆ ---                             ┆ ---     │
│ i64        ┆ str                             ┆ i64     │
╞════════════╪═════════════════════════════════╪═════════╡
│ 1          ┆ Ingeniería Aeronáutica          ┆ 1       │
│ 2          ┆ Ingeniería Ambiental            ┆ 1       │
│ 3          ┆ Ingeniería Biomédica            ┆ 1       │
│ 4          ┆ Ingeniería Biónica              ┆ 1       │
│ 5          ┆ Ingeniería Bioquímica           ┆ 1       │
│ …          ┆ …                               ┆ …       │
│ 62         ┆ Licenciatura en Mercadotecnia … ┆ 3       │
│ 63         ┆ Licenciatura en Negocios Digit… ┆ 3       │
│ 64         ┆ Licenciatura en Negocios Inter… ┆ 3       │
│ 65         ┆ Licenciatura en Relaciones Com… ┆ 3       │
│ 66         ┆ Licenciatura en Turismo         ┆ 3       │
└────────────┴─────────────────────────────────┴─────────┘