In [3]:
%pip install pandas openpyxl
import pandas as pd
from IPython.display import display


archivo = 'oferta_academicav2.2.xlsx'
all_sheets = pd.read_excel(archivo, sheet_name=None, engine='openpyxl')

for nombre, df in all_sheets.items():
    print("Hoja:", nombre, "— filas:", df.shape[0], "columnas:", df.shape[1])
    display(df.head(3))

Requirement already satisfied: pandas in c:\Users\emanu\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.6)
Requirement already satisfied: openpyxl in c:\Users\emanu\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\emanu\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\emanu\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\emanu\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: et-xmlfile in c:\Users\emanu\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\Users\emanu\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Hoja: area — filas: 3 columnas: 2

   id_area                               nombre_area
0        1  Ingeniería y Ciencias Físico Matemáticas
1        2                Ciencias Médico Biológicas
2        3       Ciencias Sociales y Administrativas

Hoja: escuela — filas: 26 columnas: 2

   id_escuela           nombre_escuela
0           1   CICS Unidad Milpa Alta
1           2  CICS Unidad Santo Tomás
2           3                     ENBA

Hoja: carrera — filas: 66 columnas: 3

   carrera_id          nombre_carrera  id_area
0           1  Ingeniería Aeronáutica        1
1           2    Ingeniería Ambiental        1
2           3    Ingeniería Biomédica        1

Hoja: habilidad — filas: 253 columnas: 2

  id_habilidad                                        descripcion
0         H001  Diseño, construcción, mantenimiento y operació...
1         H002  Proyección y puesta en operación de plantas e ...
2         H003  Investigación, adaptación y desarrollo de nuev...

Hoja: carrera_habilidad — filas: 336 columnas: 2

  id_carrera id_habilidad
0       C001         H001
1       C001         H002
2       C001         H003

#procesa archivo excel de escuelas, carreras